name: EcoSimple
main: fr.Tarzan.ecosimple.Loader
version: "${pom.version}"
api: [1.0.9]
authors:
  - Dalker(Tarzan)
  - C1oky

permissions:
  eco.command.setmoney:
    default: op
    description: Set the player a certain balance
  eco.command.givemoney:
    default: op
    description: Give a player a certain amount of money
  eco.command.balance:
    default: true
    description: View balance
  eco.command.pay:
    default: true
    description: Transferring money to another player
  eco.command.seemoney:
    default: op
    description: View another player’s balance
  eco.command.topmoney:
    default: true
    description: View list players with the best balance
